  directive @deepAuth(
    path: String
    variables: [String]
  ) on OBJECT
  
  "You are the owner or all calendars"
  type Owner @deepAuth(path:"""{ id:"$ownerId" }""", variables: ["$ownerId"]) {
    id:ID!
  }

  "Your calendars"
  type Calendar @deepAuth(path:"""{ owner:{Owner:{id:"$ownerId"}} }""", variables: ["$ownerId"]) {
    id:ID!
    timezone: String @cypher(statement:"match (this)-[:BELONGS_TO]-(tz:TZ) return tz.id limit 1")
    owner : OWNED
    events: [BELONGS_TO]
    invitedEvents : [INVITED] 
    acceptedEvents : [ACCEPTED]
    declinedEvents : [DECLINED]
    createdEvents : [BELONGS_TO]
  }

"Events in all calendars XX"
type Event @deepAuth(path:"""{calendar:{Calendar:{owner:{Owner:{id:"$ownerId"}} }}}  """, variables: ["$ownerId"]) {
  id:ID!
  calendar:BELONGS_TO
  title:String
  body:String
  startAt : String @cypher(statement:"MATCH (this) WITH com.vizipi.Procs.toDT(this, true) as starts RETURN toString(starts)")
  endAt :   String @cypher(statement:"MATCH (this) WITH com.vizipi.Procs.toDT(this, false) as starts RETURN toString(starts)")
  invitedCalendars :  [INVITED]
  acceptedCalendars : [ACCEPTED]  
  declinedCalendars : [DECLINED]
}

type BELONGS_TO @relation(name: "BELONGS_TO"){
  from: Event
  to: Calendar
  created_at: DateTime
}

type ACCEPTED @relation(name:"ACCEPTED"){
  from: Calendar
  to: Event
  created_at: DateTime
}
type DECLINED @relation(name:"DECLINED"){
  from: Calendar
  to: Event
  created_at: DateTime
}
type CREATED @relation(name:"CREATED"){
  from: Event
  to: Calendar
  created_at: DateTime
}
type INVITED @relation(name:"INVITED"){
  from: Event
  to: Calendar
  created_at: DateTime
}
type OWNED @relation(name:"OWNED"){
  from: Calendar
  to: Owner
}

type TimeSlot{
  from: DateTime
  to: DateTime
}

type Day{
  id: String
}

type Mutation {

  """
  Creates OR updates an existing calander.
  **calendarId**
  If you pass a value you will either create a new calendar with that ID or update an existing one to the specified timezone.
  If you omit the calendarId you will get a new calendar with a randon id
  """
  createOrUpdateCalendar(calendarId:String="", timeZoneOffset:String="Z"): Calendar
  @cypher(statement:"call com.vizipi.Procs.createOrUpdateCalendar($cypherParams.ownerId, $calendarId, $timeZoneOffset) yield node return node")        


  """
  Creates OR updates an existing Event.
  **eventId**
  If you pass a value you will either create a new Event with that ID or update an existing one.
  If you omit the eventId you will get a new Event with a randon id

  **calendarId**
  The calendar this event belongs to.  if the calendar does not exist it will be created ( default timezone )
  """
  createOrUpdateEvent(eventId:String="", calendarId:String!, startAt:String!, endAt:String!,title:String="",body:String=""): Event
  @cypher(statement:"call com.vizipi.Procs.createOrUpdateEvent($cypherParams.ownerId, $calendarId, DateTime($startAt), DateTime($endAt), $title,$body,$eventId) yield node return node")


  """
  This will return the first 5 time slots where all the calendarIds supplied are available.
  for example assuming event lengths are 30 minutes and these are some events per calendar
  

| Calendar 1       | Calendar 2     | Calendar 3     |
| :------------- | :----------: | -----------: |
| 2020-01-01 08:00 | 2020-01-01 08:00   | 2020-01-01 07:00    |
| 2020-01-01 10:45 | 2020-01-01 08:45   | 2020-01-01 09:25    | |

should return 
from 2020-01-01 07:30
to   2020-01-01 08:00

from 2020-01-01 09:30
to   2020-01-01 10:00

from 2020-01-01 10:00
to   2020-01-01 10:30

from 2020-01-01 11:15
to   2020-01-01 11:45

  *Note* the time zone is not yes translated :/ and need to add how large of a window is needed
  """
  checkAvailability(calendarIds:[String], fromDate:String!,toDate:String!  ): [TimeSlot]
  @cypher(statement:"call com.vizipi.Procs.checkAvailability($cypherParams.ownerId, $calendarIds, DateTime($fromDate), DateTime($toDate)) yield from, to return {from:from,to:to} as node")        


  """
  invite one or more calendars to this event  ( any non existant calendar will be created and invited )
  """
  inviteToEvent(eventId:String!, calendarIds:[String]): Event
  @cypher(statement:"call com.vizipi.Procs.EventInvite($cypherParams.ownerId, $eventId, $calendarIds) yield node return node")

  acceptInvite(eventId:String!, calendarId:String!): Event
  @cypher(statement:"call com.vizipi.Procs.AcceptInvite($cypherParams.ownerId, $eventId, $calendarId) yield node return node")  

  declineInvite(eventId:String!, calendarId:String!): Event
  @cypher(statement:"call com.vizipi.Procs.DeclineInvite($cypherParams.ownerId, $eventId, $calendarId) yield node return node")    

  unInvite(eventId:String!,  calendarIds:[String]): Event
  @cypher(statement:"call com.vizipi.Procs.EventUnInvite($cypherParams.ownerId, $eventId, $calendarIds) yield node return node")      


"""
Deletes the provided event  will return empty event or an error if you provided the wrong eventid
"""
  deleteEvent(eventId:String!): Event
  @cypher(statement:"call com.vizipi.Procs.DeleteEvent($cypherParams.ownerId, $eventId) yield node return node")      

"""
Deletes the provided calendar and all the events associated with it.  Will return empty calendar or an error if you provided the wrong calendarId
"""
  deleteCalendar(calendarId:String!): Calendar
  @cypher(statement:"call com.vizipi.Procs.DeleteCalendar($cypherParams.ownerId, $calendarId) yield node return node")      
  
}